#if !canImport(ObjectiveC)
import XCTest

extension DateTimeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DateTimeTests = [
        ("testDeserialization", testDeserialization),
        ("testGetters", testGetters),
        ("testSerialization", testSerialization),
        ("testSetters", testSetters),
    ]
}

extension LocalDateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LocalDateTests = [
        ("testDeserialization", testDeserialization),
        ("testInitInvalidation", testInitInvalidation),
        ("testInitValidation", testInitValidation),
        ("testSerialization", testSerialization),
    ]
}

extension LocalDateTimeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LocalDateTimeTests = [
        ("testDeserialization", testDeserialization),
        ("testGetters", testGetters),
        ("testSerialization", testSerialization),
        ("testSetters", testSetters),
    ]
}

extension LocalTimeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LocalTimeTests = [
        ("testDeserialization", testDeserialization),
        ("testInitInvalidation", testInitInvalidation),
        ("testInitValidation", testInitValidation),
        ("testSerialization", testSerialization),
    ]
}

extension TimeOffsetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TimeOffsetTests = [
        ("testDeserialization", testDeserialization),
        ("testInvalidation", testInvalidation),
        ("testSerialization", testSerialization),
        ("testValidation", testValidation),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DateTimeTests.__allTests__DateTimeTests),
        testCase(LocalDateTests.__allTests__LocalDateTests),
        testCase(LocalDateTimeTests.__allTests__LocalDateTimeTests),
        testCase(LocalTimeTests.__allTests__LocalTimeTests),
        testCase(TimeOffsetTests.__allTests__TimeOffsetTests),
    ]
}
#endif
