name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build release artifacts
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Xcode version
      run: sudo xcode-select -s /Applications/Xcode_11.1.app
    - name: Carthage archive
      run: make carthage-archive
    - name: Upload binaries
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: NetTime.framework.zip
        asset_name: NetTime.framework.zip
        tag: ${{ github.ref }}
        overwrite: true
