name: Sync main to master

on:
  push:
    branches:
      - main

jobs:
  sync-to-master:
    name: sync-to-master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Synchronize main and master branches
      run: |
        git checkout $TARGET_BRANCH
        git merge --ff-only $SOURCE_BRANCH
        git push origin $TARGET_BRANCH
      env:
        SOURCE_BRANCH: main
        TARGET_BRANCH: master
